export const PRODUCTLIST = 'PRODUCTLIST'
export const PRODUCTURL = 'https://fakestoreapi.com/products'
export const CARTLIST = 'CARTLIST'
export const ACTIVEUSER = 'ACTIVEUSER'
export const GETCART = 'GETCART'
export const DELETEPRODUCT = 'DELETEPRODUCT'
export const CARTSDATA = 'https://fakestoreapi.com/carts/1'
export const USERDATA = 'https://fakestoreapi.com/users/1'